import type { Exercise } from './types.js';

export const defaultExercises: Exercise[] = [
  {
    id: 'bench-press',
    name: 'Bench Press',
    aliases: ['bench', 'flat bench'],
    muscles: ['chest', 'triceps', 'front-delts'],
    type: 'compound',
    equipment: 'barbell',
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    aliases: ['incline bench', 'incline press'],
    muscles: ['chest', 'triceps', 'front-delts'],
    type: 'compound',
    equipment: 'barbell',
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    aliases: ['db bench'],
    muscles: ['chest', 'triceps', 'front-delts'],
    type: 'compound',
    equipment: 'dumbbell',
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    aliases: ['ohp', 'shoulder press', 'military press'],
    muscles: ['shoulders', 'triceps', 'front-delts'],
    type: 'compound',
    equipment: 'barbell',
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    aliases: ['db shoulder press', 'db ohp'],
    muscles: ['shoulders', 'triceps', 'front-delts'],
    type: 'compound',
    equipment: 'dumbbell',
  },
  {
    id: 'squat',
    name: 'Squat',
    aliases: ['back squat', 'barbell squat'],
    muscles: ['quads', 'glutes', 'hamstrings'],
    type: 'compound',
    equipment: 'barbell',
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    aliases: [],
    muscles: ['quads', 'glutes'],
    type: 'compound',
    equipment: 'barbell',
  },
  {
    id: 'deadlift',
    name: 'Deadlift',
    aliases: ['conventional deadlift'],
    muscles: ['back', 'hamstrings', 'glutes', 'traps'],
    type: 'compound',
    equipment: 'barbell',
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    aliases: ['rdl', 'stiff leg deadlift'],
    muscles: ['hamstrings', 'glutes', 'back'],
    type: 'compound',
    equipment: 'barbell',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    aliases: ['bent over row', 'bb row'],
    muscles: ['back', 'lats', 'biceps', 'rear-delts'],
    type: 'compound',
    equipment: 'barbell',
  },
  {
    id: 'pull-up',
    name: 'Pull Up',
    aliases: ['pullup', 'chin up'],
    muscles: ['lats', 'back', 'biceps'],
    type: 'compound',
    equipment: 'bodyweight',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    aliases: ['lat pull', 'pulldown'],
    muscles: ['lats', 'back', 'biceps'],
    type: 'isolation',
    equipment: 'cable',
  },
  {
    id: 'cable-row',
    name: 'Cable Row',
    aliases: ['seated cable row', 'seated row'],
    muscles: ['back', 'lats', 'biceps', 'rear-delts'],
    type: 'compound',
    equipment: 'cable',
  },
  {
    id: 'face-pulls',
    name: 'Face Pulls',
    aliases: ['face pull'],
    muscles: ['rear-delts', 'traps', 'back'],
    type: 'isolation',
    equipment: 'cable',
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    aliases: ['side raise', 'lat raise'],
    muscles: ['side-delts', 'shoulders'],
    type: 'isolation',
    equipment: 'dumbbell',
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    aliases: ['reverse fly', 'rear delt raise'],
    muscles: ['rear-delts', 'back'],
    type: 'isolation',
    equipment: 'dumbbell',
  },
  {
    id: 'bicep-curl',
    name: 'Bicep Curl',
    aliases: ['curl', 'dumbbell curl'],
    muscles: ['biceps'],
    type: 'isolation',
    equipment: 'dumbbell',
  },
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    aliases: ['bb curl'],
    muscles: ['biceps'],
    type: 'isolation',
    equipment: 'barbell',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    aliases: ['hammer curls'],
    muscles: ['biceps', 'forearms'],
    type: 'isolation',
    equipment: 'dumbbell',
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    aliases: ['cable pushdown', 'pushdown'],
    muscles: ['triceps'],
    type: 'isolation',
    equipment: 'cable',
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    aliases: ['lying tricep extension'],
    muscles: ['triceps'],
    type: 'isolation',
    equipment: 'barbell',
  },
  {
    id: 'dips',
    name: 'Dips',
    aliases: ['tricep dips', 'chest dips'],
    muscles: ['triceps', 'chest', 'front-delts'],
    type: 'compound',
    equipment: 'bodyweight',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    aliases: [],
    muscles: ['quads', 'glutes'],
    type: 'compound',
    equipment: 'machine',
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    aliases: ['hamstring curl', 'lying leg curl'],
    muscles: ['hamstrings'],
    type: 'isolation',
    equipment: 'machine',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    aliases: ['quad extension'],
    muscles: ['quads'],
    type: 'isolation',
    equipment: 'machine',
  },
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    aliases: ['standing calf raise'],
    muscles: ['calves'],
    type: 'isolation',
    equipment: 'machine',
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    aliases: ['barbell hip thrust'],
    muscles: ['glutes', 'hamstrings'],
    type: 'compound',
    equipment: 'barbell',
  },
  {
    id: 'lunges',
    name: 'Lunges',
    aliases: ['walking lunges', 'lunge'],
    muscles: ['quads', 'glutes', 'hamstrings'],
    type: 'compound',
    equipment: 'bodyweight',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    aliases: ['cable chest fly', 'cable crossover'],
    muscles: ['chest'],
    type: 'isolation',
    equipment: 'cable',
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck',
    aliases: ['machine fly', 'chest fly machine'],
    muscles: ['chest'],
    type: 'isolation',
    equipment: 'machine',
  },
  {
    id: 'shrugs',
    name: 'Shrugs',
    aliases: ['barbell shrug', 'dumbbell shrug'],
    muscles: ['traps'],
    type: 'isolation',
    equipment: 'barbell',
  },
  {
    id: 'plank',
    name: 'Plank',
    aliases: [],
    muscles: ['abs'],
    type: 'isolation',
    equipment: 'bodyweight',
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    aliases: ['kneeling cable crunch'],
    muscles: ['abs'],
    type: 'isolation',
    equipment: 'cable',
  },
];
